In [1]:
import numpy as np

In [2]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [3]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
arr.cumsum(axis=0)
arr.cumsum(axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])

In [7]:
rng = np.random.default_rng(seed=12345)
data = rng.standard_normal((2, 3))

In [8]:
arr = rng.standard_normal(100)
(arr > 0).sum() # Number of positive values
(arr <= 0).sum() # Number of non-positive values

50

In [9]:
bools = np.array([False, False, True, False])
bools.any()
bools.all()

False

In [10]:
arr = rng.standard_normal(6)
arr
arr.sort()
arr

array([-0.42807444, -0.12434193,  0.2019986 ,  0.78497452,  1.8482889 ,
        1.89995289])

In [11]:
arr = rng.standard_normal((5, 3))
arr

array([[-0.09842503,  0.81344544,  0.39249439],
       [ 0.7814429 ,  1.45327152,  0.82018605],
       [ 0.08770534, -0.65350565, -0.81188688],
       [-0.02553817,  1.15818454,  0.30052087],
       [ 0.05305665,  0.25727152,  0.03574286]])

In [12]:
arr.sort(axis=0)
arr
arr.sort(axis=1)
arr

array([[-0.81188688, -0.65350565, -0.09842503],
       [-0.02553817,  0.03574286,  0.25727152],
       [ 0.05305665,  0.30052087,  0.81344544],
       [ 0.08770534,  0.39249439,  1.15818454],
       [ 0.7814429 ,  0.82018605,  1.45327152]])

In [13]:
arr2 = np.array([5, -10, 7, 1, 0, -3])
sorted_arr2 = np.sort(arr2)
sorted_arr2

array([-10,  -3,   0,   1,   5,   7])

In [14]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
np.unique(names)
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [15]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [16]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

In [17]:
arr = np.arange(10)
np.save("some_array", arr)

In [18]:
np.load("some_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.savez("array_archive.npz", a=arr, b=arr)

In [20]:
arch = np.load("array_archive.npz")
arch["b"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])